### ISSUE TITLE
Simplewallet RPC send produces incorrect unlockTime value and permanently locks coins

### ISSUE THREAD

**Issue by plavirudar** [leviarcoin/leviarcoin-src#10]
This bug is identical to the one found at https://github.com/seredat/karbowanec/issues/25 

In short, sending a transaction without the `unlockTime` parameter to `simplewallet` over RPC causes a very high unlock time to be generated, effectively permanently locking coins. 

This bug is a regression from 2.1.2, since that version does not require the `unlockTime` parameter to be set. 

Example: https://explore.leviarcoin.org/transaction/3a5c30d99b1934ce2d0c01446e1610f78fc12bc448f0f86bcc04fea6e52cf38d

**Comment by markmatroska** [comment]
Fixed in newer versions
