### ISSUE TITLE
Simplewallet sees only some transactions

### ISSUE THREAD

**Issue by marki555** [leviarcoin/leviarcoin-src#12]
I have created a wallet and started mining via pool at it. However the wallet sees only some of the incoming transactions (which are shown OK in the block explorer and also in the local daemon), usually those most recent ones. I tried also using "reset", but after that I see only the last incoming transaction, so I cannot see my real balance.

It seems that while the wallet is running it sees all incoming transactions, but not when it is run for example after 2 days and synces with the daemon (daemon is running 24x7 and can see all transactions using print_tx).

Is it somehow possible to fix this?

**Comment by marki555** [comment]
I have now (after trying several workaround for 2 hours) managed to compile latest simplewallet from github and this version sees all transactions after "reset" correctly. Before I have used official cmdline binaries from your website.

**Comment by BKdilse** [comment]
I'm seeing this too, on v2.1.3, and its not synching at all now.  When I try reset, my balance gets wiped completely and after a sync its still 0.  Serious problem with the download from the official site.

**Comment by BKdilse** [comment]
got fixed in v18.06.1

**Comment by markmatroska** [comment]
Yes, closing
