### ISSUE TITLE
Unconfirmed transactions

### ISSUE THREAD

**Issue by konqueror1** [leviarcoin/leviarcoin-src#3]
Hi,
I have unconfirmed transactions stuck for 3-4 months. Tried the new wallet with full resync but withous success. These are my latest transactions:
`2018-Jan-05 12:00:25.475508 INFO    Height 80549, transaction cb8b1a65bd363495272f628d24deb745f4bf032152f678c111a62d27b0014644, spent 1000.01000000
2018-Jan-05 12:04:16.537774 INFO    Unconfirmed transaction 75709448cf6aa2c72b07000311c0e0e740a3128969f44af9f67f384e976b02b1, spent 3000.01000000
2018-Jan-05 12:04:16.560172 INFO    Unconfirmed transaction e284fceb6c2c1b12f94bf3b07a5840c9e17538b8e7f9cdde120a3222d21412fb, spent 3000.01000000
2018-Jan-05 12:04:16.584814 INFO    Unconfirmed transaction f97ceb7bc3ffa0f0ad9b74b1663b6e52f806eee6b167dc6530c33345748f0fd6, spent 3000.01000000`
How can I get these coins back to my wallet?

**Comment by leviarcoin** [comment]
Hello, wait for upcoming fork @ block 250000 (8th-9th Jan) these txs should be included in blocks then

**Comment by markmatroska** [comment]
I'm closing the issue, solved after fork
