### ISSUE TITLE
out-of-line compiling on Mac OS X

### ISSUE THREAD

**Issue by jotacor** [leviarcoin/leviarcoin-src#5]
Hi,
I'm getting the following errors when I compile in Mac OS X.

leviarcoin-src/src/SimpleWallet/SimpleWallet.cpp:1040:28: error: out-of-line definition of 'transferGui' does not match any declaration in 'CryptoNote::simple_wallet'
std::string simple_wallet::transferGui(const std::vector<std::string> &args) {
                           ^~~~~~~~~~~
leviarcoin-src/src/SimpleWallet/SimpleWallet.cpp:1123:28: error: out-of-line definition of 'getWalletAddress' does not match any declaration in 'CryptoNote::simple_wallet'
std::string simple_wallet::getWalletAddress() {
                           ^~~~~~~~~~~~~~~~
leviarcoin-src/src/SimpleWallet/SimpleWallet.cpp:1133:23: error: out-of-line definition of 'getTxsCount' does not match any declaration in 'CryptoNote::simple_wallet'
size_t simple_wallet::getTxsCount() {
                      ^~~~~~~~~~~
leviarcoin-src/src/SimpleWallet/SimpleWallet.cpp:1174:28: error: out-of-line definition of 'transferWrapper' does not match any declaration in 'CryptoNote::simple_wallet'
std::string simple_wallet::transferWrapper(const std::vector<std::string> &args) {
                           ^~~~~~~~~~~~~~~
leviarcoin-src/src/SimpleWallet/SimpleWallet.cpp:1181:21: error: out-of-line definition of 'resetWrapper' does not match any declaration in 'CryptoNote::simple_wallet'
bool simple_wallet::resetWrapper() {
                    ^~~~~~~~~~~~
leviarcoin-src/src/SimpleWallet/SimpleWallet.cpp:1186:21: error: out-of-line definition of 'saveWrapper' does not match any declaration in 'CryptoNote::simple_wallet'
bool simple_wallet::saveWrapper(std::string m_walletFilename) {
                    ^~~~~~~~~~~
6 errors generated.
make[3]: *** [src/CMakeFiles/SimpleWallet.dir/SimpleWallet/SimpleWallet.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/SimpleWallet.dir/all] Error 2

**Comment by ghost** [comment]
The same problem when building on Ubuntu 16.04 with gcc 5.4.0.

**Comment by Heliumminer** [comment]
Me too , on Ubuntu 16.04 gcc 5.4 and 6 


/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1040:76: error: no ‘std::__cxx11::string CryptoNote::simple_wallet::transferGui(const std::vector<std::__cxx11::basic_string<char> >&)’ member function declared in class ‘CryptoNote::simple_wallet’
 std::string simple_wallet::transferGui(const std::vector<std::string> &args) {
                                                                            ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1123:45: error: no ‘std::__cxx11::string CryptoNote::simple_wallet::getWalletAddress()’ member function declared in class ‘CryptoNote::simple_wallet’
 std::string simple_wallet::getWalletAddress() {
                                             ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1133:35: error: no ‘size_t CryptoNote::simple_wallet::getTxsCount()’ member function declared in class ‘CryptoNote::simple_wallet’
 size_t simple_wallet::getTxsCount() {
                                   ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1174:80: error: no ‘std::__cxx11::string CryptoNote::simple_wallet::transferWrapper(const std::vector<std::__cxx11::basic_string<char> >&)’ member function declared in class ‘CryptoNote::simple_wallet’
 std::string simple_wallet::transferWrapper(const std::vector<std::string> &args) {
                                                                                ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1181:34: error: no ‘bool CryptoNote::simple_wallet::resetWrapper()’ member function declared in class ‘CryptoNote::simple_wallet’
 bool simple_wallet::resetWrapper() {
                                  ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1186:61: error: no ‘bool CryptoNote::simple_wallet::saveWrapper(std::__cxx11::string)’ member function declared in class ‘CryptoNote::simple_wallet’
 bool simple_wallet::saveWrapper(std::string m_walletFilename) {
                                                             ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp: In function ‘void reset_helper(std::__cxx11::string, CryptoNote::simple_wallet&)’:
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1203:12: error: ‘class CryptoNote::simple_wallet’ has no member named ‘resetWrapper’
     wallet.resetWrapper();
            ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp: In function ‘void save_helper(std::__cxx11::string, CryptoNote::simple_wallet&)’:
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1242:12: error: ‘class CryptoNote::simple_wallet’ has no member named ‘saveWrapper’
     wallet.saveWrapper(m_wallet_file_gui);
            ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp: In function ‘void tx_helper(std::__cxx11::string, CryptoNote::simple_wallet&)’:
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1355:33: error: ‘class CryptoNote::simple_wallet’ has no member named ‘transferWrapper’
     std::string result = wallet.transferWrapper(args);
                                 ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp: In function ‘void gui_helper(std::__cxx11::string, CryptoNote::simple_wallet&)’:
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1473:46: error: ‘class CryptoNote::simple_wallet’ has no member named ‘getWalletAddress’
   writeAddressFile(file_name_address, wallet.getWalletAddress());
                                              ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1467:9: warning: unused variable ‘lastTxsCount’ [-Wunused-variable]
  size_t lastTxsCount = 0;
         ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp: In function ‘void gui_helper_rpc(std::__cxx11::string, Tools::wallet_rpc_server&)’:
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1514:9: warning: unused variable ‘lastTxsCount’ [-Wunused-variable]
  size_t lastTxsCount = 0;
         ^
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp: In function ‘int main(int, char**)’:
/crypto/demon/xlc/src/SimpleWallet/SimpleWallet.cpp:1789:24: error: ‘class CryptoNote::simple_wallet’ has no member named ‘resetWrapper’
    if (gui_import) wal.resetWrapper();
                        ^
src/CMakeFiles/SimpleWallet.dir/build.make:86: recipe for target 'src/CMakeFiles/SimpleWallet.dir/SimpleWallet/SimpleWallet.cpp.o' failed
make[2]: *** [src/CMakeFiles/SimpleWallet.dir/SimpleWallet/SimpleWallet.cpp.o] Error 1
CMakeFiles/Makefile2:378: recipe for target 'src/CMakeFiles/SimpleWallet.dir/all' failed


**copule days earlier it compile without error.**
Any help ? :(

**Comment by markmatroska** [comment]
This is solved in the last commit
