### ISSUE TITLE
 WARNING CHECKPOINT FAILED FOR HEIGHT 250001

### ISSUE THREAD

**Issue by zairoo** [leviarcoin/leviarcoin-src#8]
2018-Feb-04 01:39:30.138849 WARNING CHECKPOINT FAILED FOR HEIGHT 250001. EXPECTED HASH: c4b96c8c66c44aa9aaed5a37e05754efc895ef97be19ac0775d4bea9cdef19a2, FETCHED HASH: fabb481b67c8770868e0390fbde582b2988e27a0f6be6c23ed900c7e7ea1f85f

too many such warnings!!!!

**Comment by Bathmat** [comment]
Same issue here. When I downloaded the blockchain from Leviarcoin.org, I got the problem right away. When I sync'd the blockchain from 0, I got this: 

`2018-Feb-26 02:58:22.755925 INFO    CHECKPOINT PASSED FOR INDEX 250001 c4b96c8c66c44aa9aaed5a37e05754efc895ef97be19ac0775d4bea9cdef19a2
2018-Feb-26 02:58:53.812892 WARNING CHECKPOINT FAILED FOR HEIGHT 250001. EXPECTED HASH: c4b96c8c66c44aa9aaed5a37e05754efc895ef97be19ac0775d4bea9cdef19a2, FETCHED HASH: fabb481b67c8770868e0390fbde582b2988e27a0f6be6c23ed900c7e7ea1f85f
2018-Feb-26 02:58:53.813322 WARNING Checkpoint block hash mismatch for block fabb481b67c8770868e0390fbde582b2988e27a0f6be6c23ed900c7e7ea1f85f`

So it looks like it passed initially, then fails.

**Comment by tenpin784** [comment]
The problem is not your installation, it is the remote end. As long as you updated your side, then you should be fine, and that is warning you that the far end has not updated their side.

**Comment by Bathmat** [comment]
Yeah, I haven't seen many (if any) of these warnings recently. This can probably be closed.

**Comment by tenpin784** [comment]
I am sure it will happen again when they fork at 325000

I am working on updating my daemons now to test it out.

**Comment by Bathmat** [comment]
I've already updated mine to the newest code changes and haven't had any issues, but I guess we'll see at the fork block like you said.
